/**
 * Banco de temas do "Efeito Manada" (Herd Mentality). Cada tema e um prompt
 * ABERTO: os jogadores tentam escrever a MESMA resposta que a maioria. Nao ha
 * resposta "certa" — o objetivo e pensar como a manada. Todos em pt-BR,
 * pensados para ter poucas respostas obvias (para a maioria se formar).
 */
export const MANADA_THEMES: readonly string[] = [
  'Um condimento que vai no cachorro-quente',
  'Nomeie um animal de fazenda',
  'Uma cor que não seja primária',
  'Uma marca de refrigerante',
  'Uma fruta amarela',
  'Um esporte jogado com bola',
  'Um super-herói',
  'Algo que você põe no pão de manhã',
  'Um país da Europa',
  'Uma parte do corpo com 4 letras',
  'Um dia da semana',
  'Uma pizza clássica',
  'Um instrumento musical',
  'Algo que se encontra numa praia',
  'Um personagem da Disney',
  'Uma bebida quente',
  'Um meio de transporte',
  'Um animal que vive na água',
  'Uma profissão',
  'Algo que existe numa cozinha',
  'Uma estação do ano',
  'Um planeta do Sistema Solar',
  'Uma rede social',
  'Um doce de festa junina',
  'Um time de futebol brasileiro',
  'Uma cor de semáforo',
  'Um número entre 1 e 10',
  'Algo gelado',
  'Um sabor de sorvete',
  'Uma peça de roupa',
  'Um móvel da sala',
  'Um tipo de pão',
  'Um animal de estimação comum',
  'Algo que voa',
  'Uma marca de carro',
  'Uma matéria da escola',
  'Um cômodo da casa',
  'Uma comida típica brasileira',
  'Algo redondo',
  'Um verbo terminado em "ar"',
  'Uma flor',
  'Um continente',
  'Algo que se usa na chuva',
  'Uma bebida alcoólica',
  'Um tempero de cozinha',
  'Um brinquedo de criança',
  'Uma cor de cabelo',
  'Um eletrodoméstico',
  'Algo que se compra na padaria',
  'Um jogo de tabuleiro',
  'Uma parte do carro',
  'Um animal do zoológico',
  'Algo que se leva para a praia',
  'Uma fruta vermelha',
  'Um filme de animação',
  'Um utensílio para comer',
  'Uma capital brasileira',
  'Algo que dá medo',
  'Um sabor de pizza doce',
  'Um mês do ano',
  'Uma cor de vaca',
  'Algo que se acha num quintal',
  'Uma marca de tênis',
  'Um herói de desenho animado',
  'Algo que se guarda na geladeira',
  'Uma palavra que rima com "amor"',
  'Um animal que faz barulho de noite',
  'Uma sobremesa gelada',
  'Algo que toda festa de aniversário tem',
  'Uma cor de olho',
];
