/**
 * Temas/perguntas simples (peça de Tema, fundo rosa). O jogador deve dizer uma
 * resposta do tema começando com a Letra vizinha. Inclui os temas religiosos
 * citados pelo usuário além de uma variedade geral.
 */
export const STOPCONNECT_THEMES: string[] = [
  'Esporte',
  'Filme',
  'Fruta',
  'País',
  'Cidade',
  'Profissão',
  'Cor',
  'Prato típico',
  'Marca',
  'Personagem fictício',
  'Nome de figura religiosa',
  'Instrumento musical',
  'Time esportivo',
  'Parte do corpo',
  'Flor',
  'Bebida',
  'Doce',
  'Desenho animado',
  'Série de TV',
  'Livro',
  'Objeto de casa',
  'Peça de roupa',
  'Meio de transporte',
  'Móvel',
  'Ferramenta',
  'Ave',
  'Animal aquático',
  'Frutos do mar',
  'Inseto',
  'Planeta ou estrela',
  'Personagem bíblico',
  'Festa ou feriado',
  'Jogo de video-game',
  'Super-herói',
  'Legume',
  'Mamífero',
  'Reptil ou anfíbio',
  'Protagonista',
  'Idioma',
  'Usa eletricidade',
  'Jogo de tabuleiro',
  'Carro (Modelo ou marca)',
  'Atleta famoso',
  'Ator internacional',
  'Atriz internacional',
  'Cantor ou banda internacional',
  'Ator brasileiro',
  'Atriz brasileira',
  'Cantor ou banda brasileira',
  'Utensílio de cozinha',
  'Objeto de escritório',
  'Alimento',
  'Acessório',
  'Software ou aplicativo',
  'Verdura',
  'Marca',
  'Filme de animação',
  'Brinquedo',
  'Comida de rua',
  'Material escolar',
  'Material de construção',
  'Árvore ou planta',
  'Pedra preciosa ou mineral',
  'Elemento químico',
  'Local',
  'Moeda',
  'Vilão',
  'Pokémon',
  'Programa de TV',
  'Super poder',
  'Arma',
  'Sentimento',
  'Doença'
];
