/**
 * Temas/perguntas simples (peça de Tema, fundo rosa). O jogador deve dizer uma
 * resposta do tema começando com a Letra vizinha. Inclui os temas religiosos
 * citados pelo usuário além de uma variedade geral.
 */
export const STOPCONNECT_THEMES: string[] = [
  'Esporte',
  'Filme',
  'Fruta',
  'País',
  'Cidade',
  'Profissão',
  'Cor',
  'Prato típico',
  'Marca',
  'Personagem fictício',
  'Nome de Santo ou Santa',
  'Instrumento musical',
  'Time de futebol',
  'Parte do corpo',
  'Flor',
  'Bebida',
  'Doce',
  'Desenho animado',
  'Série de TV',
  'Livro',
  'Objeto de casa',
  'Peça de roupa',
  'Meio de transporte',
  'Móvel',
  'Ferramenta',
  'Ave',
  'Peixe',
  'Inseto',
  'Planeta ou estrela',
  'Personagem bíblico',
  'Festa ou feriado',
  'Jogo de video-game',
  'Super-herói',
  'Legume',
  'Usa pilha',
  'Precisa de tomada',
  'Usa água',
  'Usa eletricidade',
  'Jogo de tabuleiro',
  'Carro (Modelo ou marca)',
  'Atleta famoso',
  'Ator internacional',
  'Atriz internacional',
  'Cantor ou banda internacional',
  'Ator brasileiro',
  'Atriz brasileira',
  'Cantor ou banda brasileira',
  'Utensílio de cozinha',
  'Objeto de escritório' 
];
