/**
 * Temas/perguntas simples (peça de Tema, fundo rosa). O jogador deve dizer uma
 * resposta do tema começando com a Letra vizinha. Inclui os temas religiosos
 * citados pelo usuário além de uma variedade geral.
 */
export const STOPCONNECT_THEMES: string[] = [
  'Esporte',
  'Filme',
  'Fruta',
  'País',
  'Cidade',
  'Animal',
  'Profissão',
  'Cor',
  'Comida',
  'Marca',
  'Personagem',
  'Nome de Santo ou Santa',
  'Objeto religioso',
  'Nome próprio',
  'Instrumento musical',
  'Time de futebol',
  'Parte do corpo',
  'Flor',
  'Bebida',
  'Doce',
  'Desenho animado',
  'Série de TV',
  'Cantor ou banda',
  'Livro',
  'Objeto de casa',
  'Peça de roupa',
  'Meio de transporte',
  'Móvel',
  'Ferramenta',
  'Ave',
  'Peixe',
  'Inseto',
  'Planeta ou estrela',
  'Personagem bíblico',
  'Festa ou feriado',
  'Jogo',
  'Super-herói',
  'Legume',
];
